# Generated by Django 5.0.2 on 2025-11-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_remove_maestros_edad_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
